name: Compile Go 

on:
  workflow_dispatch: 

jobs:
  build:
    strategy:
  
      fail-fast: false 
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
          
          - os: macos-13
            goos: darwin
            goarch: amd64

          - os: macos-14
            goos: darwin
            goarch: arm64
            
          - os: windows-latest
            goos: windows
            goarch: amd64

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'


    - name: Install Linux Dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y xorg-dev libgl1-mesa-dev

    - name: Build Binary
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        CGO_ENABLED: 1 
      shell: bash
      run: |
        EXT=""
        if [ "$GOOS" = "windows" ]; then
          EXT=".exe"
        fi
        
        go build -v -o myapp-${{ matrix.goos }}-${{ matrix.goarch }}$EXT ./...

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: 32-bit-squadron-${{ matrix.goos }}-${{ matrix.goarch }}
        path: 32-bit-squadron-${{ matrix.goos }}-${{ matrix.goarch }}*
